### ISSUE TITLE
Dynamic text support ? 

### ISSUE THREAD

**Issue by jkanchelov** [jiborobot/pixi-animate-extension#27]
Was it considered to be able to change the text in a textfield runtime and is it possible to accomplish ?

**Comment by bigtimebuddy** [comment]
Yes! All text is dynamic in PIXI. If you give a text field an instance name within Animate (e.g. "myInput") you can then address the field dynamically as a property of the MovieClip it's within. 

For instance, you can use the callback after loading the PixiAnimate stage, to get a reference to  your text field object (PIXI.Text)

```js
PIXI.animate.load(lib.MyStage, stage, function(instance){
    instance.myInput.text = "Hello!";
});
```

**Comment by jkanchelov** [comment]
Super ! I was maybe mistaken by the [documentation](http://jiborobot.github.io/pixi-animate/PIXI.Text.html), because I didn't saw it as prop and didn't tried it.
