### ISSUE TITLE
No Spritesheet published only .txt or .json

### ISSUE THREAD

**Issue by lewislong** [jiborobot/pixi-animate-extension#28]
I can only seem to publish the data for drawing the graphics objects in Pixi.
Whether or not I have "Export Spritesheets" selected, I only get the vector data for my movieclips. Perhaps it's user error. I was following the jibo aquarium tutorial and stopped when checking to see if my spritesheet published.

**Comment by bigtimebuddy** [comment]
Are you sure your FLA contains bitmaps? Spritesheets are only exported if you have bitmaps in your FLA. Vectors are not automatically converted to bitmaps.

**Comment by lewislong** [comment]
User Error!

Have you guys thought about adding it as a feature? If you could generate texture atlas' that replaced the vector shapes but used the same animate.MovieClip class in the runtime, this would be amazing.

I know we can cache the vectors at runtime and this is what I am currently doing at my day job working on EaselJS powered games. I've run into GC and memory limit issues on lower end devices and Pixi has performed a lot better in tests with standard sprite based assets.

I have animations where there are many characters but use the same basic images for limbs and they are transformed at runtime so standard sprites aren't really an option.

Having that one-click publishing to get MovieClips that use a texture atlas instead of vector shapes would be a massive bonus over what Adobe provide with their native canvas export.

Sorry for my own confusion here. I just need to convert the shapes in my document to bitmaps then and recomposite.

**Comment by bigtimebuddy** [comment]
There is a lot of value in being able to use both vectors and bitmaps and it's not trivial to convert all vectors in the way you're describing. However, check out this: https://github.com/SpringRoll/FlashToolkit/blob/master/src/Commands/Utilities/Copy%20Layers%20To%20Bitmap.jsfl

It's a JSFL utility I made for non-destructively converting vectors to bitmaps on each frame of a MovieClip. We use this a lot on project to help manage the conversion to bitmaps. It also gives you more flexibility for optimization. Keeping somethings as graphics and some as sprites.

**Comment by lewislong** [comment]
I must have missed that JSFL from the Flashtoolkit. I have been using some of the other SpringRoll scripts :D I got halfway through writing my own before I saw this message. I've been working with svg graphics and now canvas with vectors and bitmaps for a while now. Only just upgrading some projects to Pixi JS as it seems to perform better on iPad Mini 1st gen and similar devices for some games I make at my day job.
I use Spine on personal Unity game projects but can't convince my company or the artists here to buy it and learn a new application since they've been flash users for years. Looking for a similar solution using Adobe Animate. Seems like I'm close now so thank you for your help.

I might try and pick up a Jibo too, it looks awesome :D

**Comment by lewislong** [comment]
I think what I'm trying to achieve is quite specific. The CopyLayersToBitmap.jsfl gets me part way there but due to the fla setup artists at my company have with existing assets, it doesn't quite to the job.

I'm going to spend some time with it over the weekend and attempt to come up with something that will automate what I need but try to come up with a generic workflow to the asset creation process while I'm at it. Once I'm done I'll make a link to it here along with a test project to see it in action. I'd be grateful and interested to get some professional feedback on it from someone outside my company to help make it into something useful for others. Hopefully it'll be interesting and helpful to someone.

FYI: Pixi-animate is now working great for me and is quite the extension. I specifically love that you disabled features in the Animate UI that won't work correctly with PixiJS. If I get the results I'm expecting from this r&d (i.e. significant performance gains and memory reduction vs the current EaselJS version) then we will use it as a process to create future games. Preventing our artists from using Animate features they used to use in swf based content will make everyones life a little easier and trim down time spent in art signoff's and raised bugs.

**Comment by bigtimebuddy** [comment]
Thanks for the comments! I hope that the extension can fulfill your needs. While a bunch of people have been using in production this year during our closed beta (including the PixiJS creators), I'm excited to see where the extension goes. As you use it more, am open to feedback you or your team might have.

We could, for instance, add support for filters and other items that are currently disabled in Animate's UI (like you mentioned). Many of these things are available in PIXI, but I haven't been able to hook them up yet. Also, thinking about HTML templates for output, more spritesheet controls, audio playback improvements, optimizing output animations for filesize. Lots of room to grow!

**Comment by lewislong** [comment]
Great, I'll be sure to get involved on HTML5 dev forums and anywhere else you can recommend where these discussions are already taking place. Sometimes it takes usage in a production environment to highlight key issues or find useful features to add.
