### ISSUE TITLE
ReferenceError: sound not defined

### ISSUE THREAD

**Issue by jamaalsawyerd** [jiborobot/pixi-animate-extension#29]
Hi, I am playing around with pixi-animate to get a feel for what is possible and what is not. When I attempt to export an animation with sound I am getting the error "ReferenceError: sound not defined". Does the pixi-animate export not allow for sound, or am I doing something wrong?

![screen shot 2017-01-16 at 1 35 54 pm](https://cloud.githubusercontent.com/assets/1755430/21995110/1af7c9b4-dbf1-11e6-8c2f-7b91f1af84cc.png)

**Comment by ianmcgregor** [comment]
Did a bit of investigation. 

It doesn't break when building the debug version of the plugin from the source (`gulp --debug --install`).

With the non-debug version I get the same error. This is where the sound variable is created:

https://github.com/jiborobot/pixi-animate-extension/blob/master/src/extension/publish/items/Timeline.js#L233

It looks like `library.createInstance` is returning undefined.

```
ReferenceError: sound is not defined
    at r.commands.filter.map.e (/Library/Application Support/Adobe/CEP/extensions/com.jibo.PixiAnimate/publish/index.js:9:996)
    at Array.map (native)
    at /Library/Application Support/Adobe/CEP/extensions/com.jibo.PixiAnimate/publish/index.js:9:922
    at Array.forEach (native)
    at s.u.getFrameScripts (/Library/Application Support/Adobe/CEP/extensions/com.jibo.PixiAnimate/publish/index.js:9:761)
    at s.u.getContents (/Library/Application Support/Adobe/CEP/extensions/com.jibo.PixiAnimate/publish/index.js:8:28260)
    at s.u.render (/Library/Application Support/Adobe/CEP/extensions/com.jibo.PixiAnimate/publish/index.js:8:28159)
    at /Library/Application Support/Adobe/CEP/extensions/com.jibo.PixiAnimate/publish/index.js:8:8878
    at Array.forEach (native)
    at a.s.getTimelines (/Library/Application Support/Adobe/CEP/extensions/com.jibo.PixiAnimate/publish/index.js:8:8853)
```

**Comment by jamaalsawyerd** [comment]
Is that an easy fix? I didn't build the extension, just grabbed what was on the CC extension library. Just curious, it should be able to play sound then? That's pretty rocking if so!

**Comment by bigtimebuddy** [comment]
@ianmcgregor would appreciate a review of that PR #30, because I had to change some of your code. This resolved this issue.

The issue was probably with the argument destructuring or the rest parameters. Uglify currently doesn't fully support all ES6 features, so it's doing some funny business with those bits. Either way, that PR rewrites some of this code in ES5.

@jamaalsawyerd Keep in mind that we do not fully support sound, we only output the sound data. You can use some other library to do your audio playback by listening to `play` events on `PIXI.animate.sound`. For instance:

```js
PIXI.animate.sound.on('play', function(alias, loop) {
   // handle sound events here
});
```

**Comment by ianmcgregor** [comment]
Have reviewed the PR and looks good. @jamaalsawyerd as @bigtimebuddy mentioned you need some other library or code to actually play the sound.

You can get access to the sound data through `loader.resources`. Simple example:

```
const loader = PIXI.animate.load(lib.MyStage, stage);

PIXI.animate.sound.on('play', function(alias, loop) {
    const sound = loader.resources[alias].data;
    sound.loop = loop;
    sound.play();
});
```
