### ISSUE TITLE
Packaging spritesheet is blank

### ISSUE THREAD

**Issue by bdanis** [jiborobot/pixi-animate-extension#42]
I am trying to package a file, but it seems to have an issue reading image sizes for the spritesheet, all images are of width and height of 0.

I tried creating a createJS project, and the spritesheet created correctly

I installed the plugin using the Extension Manager (NPM and the likes are all installed)

Is there something that needed to be installed that I missed?

**Comment by bigtimebuddy** [comment]
Could you post an example FLA that we can look at?

**Comment by bdanis** [comment]
[test.fla.zip](https://github.com/jiborobot/pixi-animate-extension/files/1264873/test.fla.zip)

**Comment by bigtimebuddy** [comment]
Only PNG images are added to spritesheets so your JPG should not be added. There's probably a bug here because the spritesheets should not get exported without any PNG images.

**Comment by bdanis** [comment]
the export works on one computer, but not the new one... The computer for which it works has been running flash projects forever, so it might have a necessary lib installed somehow

**Comment by bigtimebuddy** [comment]
What does it mean that the export doesn't work? It doesn't publish at all? Are there any trace statements in Animate's output panel?

**Comment by bdanis** [comment]
it creates a js file, as well as a json file and png file for the spritesheet, but the json file has the list of images, but they all have a w and h of 8

{“frames”:{“shadow”:{“frame”:{“x”:1,“y”:1,“w”:0,“h”:0},“sourceSize”:{“w”:0,“h”:0}},“tree”:{“frame”:{“x”:3,“y”:1,“w”:0,“h”:0},“sourceSize”:{“w”:0,“h”:0}},“tree4":{“frame”:{“x”:5,“y”:1,“w”:0,“h”:0},“sourceSize”:{“w”:0,“h”:0}},“tree3”:{“frame”:{“x”:7,“y”:1,“w”:0,“h”:0},“sourceSize”:{“w”:0,“h”:0}},“tree2":{“frame”:{“x”:9,“y”:1,“w”:0,“h”:0},“sourceSize”:{“w”:0,“h”:0}},“Background”:{“frame”:{“x”:11,“y”:1,“w”:0,“h”:0},“sourceSize”:{“w”:0,“h”:0}}},“meta”:{“app”:“PixiAnimate”,“scale”:0.5,“image”:“view_sc1_end_atlas_1.png”,“size”:{“w”:2048,“h”:2048}}}

**Comment by klimivan** [comment]
Is there any progress with this issue? We are having the very same problem. Generated spritesheet is empty and in json file all images have 0 width and 0 height. Win 10, Animate CC, add on via sync.
Would anyone be kind enough to provide simple minimalistic fla where an image is exported to spritesheet upon export, so we can test for possible user error?

**Comment by Ch1pStar** [comment]
Electron versions above 1.6.15 cause this. Switch to 1.6.15 or older and it will be fine.

**Comment by kburke3** [comment]
I am also having this issue.

**Comment by abdulgalimov** [comment]
I am also having this issue.

`w=0` and `h=0` in frames.

Is it possible to fix this?

**Comment by abdulgalimov** [comment]
If you unmark Export as Spritesheets in the Publish settings - then everything works. 
But I need Spritesheet.

**Comment by abdulgalimov** [comment]
solved a problem:
```
npm -g uninstall electron
npm -g install electron@1.6.15
```
node version = v9.2.0
