### ISSUE TITLE
I am not able to install Pixi-Animate extension on my Adobe Animate CC 2018. 

### ISSUE THREAD

**Issue by singhbuy** [jiborobot/pixi-animate-extension#56]
I recently saw that pixi-animate has been acquired as an extention by adobe creative cloud and tried the various extension installers to install pixi-animate.
https://www.adobeexchange.com/creativecloud.details.14345.html

I had the npm and electron also installed as per - where to find on the above page.

_In order to use PixiAnimate, you must install Electron with NPM. If you're doing this for the first time, please install NodeJS and then run ”npm install electron -g”.

To create a new PixiAnimate document, open File -> New and select ”PixiAnimate (Custom)” from the Type list on the left._

But somehow I end up not seeing the pixi-animate option in my Animate. Can you please share guidelines on how to install it.

**Comment by singhbuy** [comment]
Issue no longer exists. Was able to install the zxp using Anastasiy Extension manager.

**Comment by bigtimebuddy** [comment]
Working on publishing the latest version now. Extension manager instructions are in the readme.

**Comment by IJsLauw** [comment]
I have the same/similar problem on 2019. Where to specify the document type?

**Comment by riscovo** [comment]
Same problem here, not managing to install on 2019.

**Comment by bigtimebuddy** [comment]
We need to build and upload a new version to Adobe Exchange marketplace. I believe if you build the plugin from source, it should work for 2019+
